export const Links = [
  'https://devicons.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/typescript/typescript-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/react/react-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/redux/redux-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/nodejs/nodejs-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/mongodb/mongodb-original-wordmark.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/express/express-original-wordmark.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/sass/sass-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/html5/html5-original-wordmark.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/css3/css3-original-wordmark.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/c/c-original.svg ',
  'https://devicons.github.io/devicon/devicon.git/icons/cplusplus/cplusplus-original.svg',
  'https://devicons.github.io/devicon/devicon.git/icons/linux/linux-original.svg',
];
